pip: fix setuptool upgrade issue
During the build image, there is an issue with the
upgrade of setuptools. Removing this upgrade to fix
this issue.
ImportError: No module named six.moves
Change-Id: I7ea4c86fb780ac42ae4d7247dd830ef9f4cbe33a